db_to_i_offset: 2
input:
  hall_call:
    hall_call_up_1: DB10.DBX0.0
    hall_call_up_2: DB10.DBX0.1
    hall_call_up_3: DB10.DBX0.2
    hall_call_up_4: DB10.DBX0.3
    hall_call_up_5: DB10.DBX0.4
    hall_call_up_6: DB10.DBX0.5
    hall_call_up_7: DB10.DBX0.6
    hall_call_up_8: DB10.DBX0.7
    hall_call_up_9: DB10.DBX1.0
    hall_call_down_2: DB10.DBX1.1
    hall_call_down_3: DB10.DBX1.2
    hall_call_down_4: DB10.DBX1.3
    hall_call_down_5: DB10.DBX1.4
    hall_call_down_6: DB10.DBX1.5
    hall_call_down_7: DB10.DBX1.6
    hall_call_down_8: DB10.DBX1.7
    hall_call_down_9: DB10.DBX2.0
    hall_call_down_10: DB10.DBX2.1
  per_car:
    '1':
      cabin_button_1: DB10.DBX2.2
      cabin_button_2: DB10.DBX2.3
      cabin_button_3: DB10.DBX2.4
      cabin_button_4: DB10.DBX2.5
      cabin_button_5: DB10.DBX2.6
      cabin_button_6: DB10.DBX2.7
      cabin_button_7: DB10.DBX3.0
      cabin_button_8: DB10.DBX3.1
      cabin_button_9: DB10.DBX3.2
      cabin_button_10: DB10.DBX3.3
      door_open_button: DB10.DBX3.4
      door_close_button: DB10.DBX3.5
      light_curtain: DB10.DBX3.6
      overload: DB10.DBX3.7
      service_mode: DB10.DBX4.0
      car_door_lock: DB10.DBX4.1
      floor_door_lock_1: DB10.DBX4.2
      floor_door_lock_2: DB10.DBX4.3
      floor_door_lock_3: DB10.DBX4.4
      floor_door_lock_4: DB10.DBX4.5
      floor_door_lock_5: DB10.DBX4.6
      floor_door_lock_6: DB10.DBX4.7
      floor_door_lock_7: DB10.DBX5.0
      floor_door_lock_8: DB10.DBX5.1
      floor_door_lock_9: DB10.DBX5.2
      floor_door_lock_10: DB10.DBX5.3
      door_open_done: DB10.DBX5.4
      door_close_done: DB10.DBX5.5
      level_up: DB10.DBX5.6
      level_down: DB10.DBX5.7
      top_limit_1: DB10.DBX6.0
      top_limit_2: DB10.DBX6.1
      bottom_limit_1: DB10.DBX6.2
      bottom_limit_2: DB10.DBX6.3
    '2':
      cabin_button_1: DB10.DBX6.4
      cabin_button_2: DB10.DBX6.5
      cabin_button_3: DB10.DBX6.6
      cabin_button_4: DB10.DBX6.7
      cabin_button_5: DB10.DBX7.0
      cabin_button_6: DB10.DBX7.1
      cabin_button_7: DB10.DBX7.2
      cabin_button_8: DB10.DBX7.3
      cabin_button_9: DB10.DBX7.4
      cabin_button_10: DB10.DBX7.5
      door_open_button: DB10.DBX7.6
      door_close_button: DB10.DBX7.7
      light_curtain: DB10.DBX8.0
      overload: DB10.DBX8.1
      service_mode: DB10.DBX8.2
      car_door_lock: DB10.DBX8.3
      floor_door_lock_1: DB10.DBX8.4
      floor_door_lock_2: DB10.DBX8.5
      floor_door_lock_3: DB10.DBX8.6
      floor_door_lock_4: DB10.DBX8.7
      floor_door_lock_5: DB10.DBX9.0
      floor_door_lock_6: DB10.DBX9.1
      floor_door_lock_7: DB10.DBX9.2
      floor_door_lock_8: DB10.DBX9.3
      floor_door_lock_9: DB10.DBX9.4
      floor_door_lock_10: DB10.DBX9.5
      door_open_done: DB10.DBX9.6
      door_close_done: DB10.DBX9.7
      level_up: DB10.DBX10.0
      level_down: DB10.DBX10.1
      top_limit_1: DB10.DBX10.2
      top_limit_2: DB10.DBX10.3
      bottom_limit_1: DB10.DBX10.4
      bottom_limit_2: DB10.DBX10.5
    '3':
      cabin_button_1: DB10.DBX10.6
      cabin_button_2: DB10.DBX10.7
      cabin_button_3: DB10.DBX11.0
      cabin_button_4: DB10.DBX11.1
      cabin_button_5: DB10.DBX11.2
      cabin_button_6: DB10.DBX11.3
      cabin_button_7: DB10.DBX11.4
      cabin_button_8: DB10.DBX11.5
      cabin_button_9: DB10.DBX11.6
      cabin_button_10: DB10.DBX11.7
      door_open_button: DB10.DBX12.0
      door_close_button: DB10.DBX12.1
      light_curtain: DB10.DBX12.2
      overload: DB10.DBX12.3
      service_mode: DB10.DBX12.4
      car_door_lock: DB10.DBX12.5
      floor_door_lock_1: DB10.DBX12.6
      floor_door_lock_2: DB10.DBX12.7
      floor_door_lock_3: DB10.DBX13.0
      floor_door_lock_4: DB10.DBX13.1
      floor_door_lock_5: DB10.DBX13.2
      floor_door_lock_6: DB10.DBX13.3
      floor_door_lock_7: DB10.DBX13.4
      floor_door_lock_8: DB10.DBX13.5
      floor_door_lock_9: DB10.DBX13.6
      floor_door_lock_10: DB10.DBX13.7
      door_open_done: DB10.DBX14.0
      door_close_done: DB10.DBX14.1
      level_up: DB10.DBX14.2
      level_down: DB10.DBX14.3
      top_limit_1: DB10.DBX14.4
      top_limit_2: DB10.DBX14.5
      bottom_limit_1: DB10.DBX14.6
      bottom_limit_2: DB10.DBX14.7
    '4':
      cabin_button_1: DB10.DBX15.0
      cabin_button_2: DB10.DBX15.1
      cabin_button_3: DB10.DBX15.2
      cabin_button_4: DB10.DBX15.3
      cabin_button_5: DB10.DBX15.4
      cabin_button_6: DB10.DBX15.5
      cabin_button_7: DB10.DBX15.6
      cabin_button_8: DB10.DBX15.7
      cabin_button_9: DB10.DBX16.0
      cabin_button_10: DB10.DBX16.1
      door_open_button: DB10.DBX16.2
      door_close_button: DB10.DBX16.3
      light_curtain: DB10.DBX16.4
      overload: DB10.DBX16.5
      service_mode: DB10.DBX16.6
      car_door_lock: DB10.DBX16.7
      floor_door_lock_1: DB10.DBX17.0
      floor_door_lock_2: DB10.DBX17.1
      floor_door_lock_3: DB10.DBX17.2
      floor_door_lock_4: DB10.DBX17.3
      floor_door_lock_5: DB10.DBX17.4
      floor_door_lock_6: DB10.DBX17.5
      floor_door_lock_7: DB10.DBX17.6
      floor_door_lock_8: DB10.DBX17.7
      floor_door_lock_9: DB10.DBX18.0
      floor_door_lock_10: DB10.DBX18.1
      door_open_done: DB10.DBX18.2
      door_close_done: DB10.DBX18.3
      level_up: DB10.DBX18.4
      level_down: DB10.DBX18.5
      top_limit_1: DB10.DBX18.6
      top_limit_2: DB10.DBX18.7
      bottom_limit_1: DB10.DBX19.0
      bottom_limit_2: DB10.DBX19.1
    '5':
      cabin_button_1: DB10.DBX19.2
      cabin_button_2: DB10.DBX19.3
      cabin_button_3: DB10.DBX19.4
      cabin_button_4: DB10.DBX19.5
      cabin_button_5: DB10.DBX19.6
      cabin_button_6: DB10.DBX19.7
      cabin_button_7: DB10.DBX20.0
      cabin_button_8: DB10.DBX20.1
      cabin_button_9: DB10.DBX20.2
      cabin_button_10: DB10.DBX20.3
      door_open_button: DB10.DBX20.4
      door_close_button: DB10.DBX20.5
      light_curtain: DB10.DBX20.6
      overload: DB10.DBX20.7
      service_mode: DB10.DBX21.0
      car_door_lock: DB10.DBX21.1
      floor_door_lock_1: DB10.DBX21.2
      floor_door_lock_2: DB10.DBX21.3
      floor_door_lock_3: DB10.DBX21.4
      floor_door_lock_4: DB10.DBX21.5
      floor_door_lock_5: DB10.DBX21.6
      floor_door_lock_6: DB10.DBX21.7
      floor_door_lock_7: DB10.DBX22.0
      floor_door_lock_8: DB10.DBX22.1
      floor_door_lock_9: DB10.DBX22.2
      floor_door_lock_10: DB10.DBX22.3
      door_open_done: DB10.DBX22.4
      door_close_done: DB10.DBX22.5
      level_up: DB10.DBX22.6
      level_down: DB10.DBX22.7
      top_limit_1: DB10.DBX23.0
      top_limit_2: DB10.DBX23.1
      bottom_limit_1: DB10.DBX23.2
      bottom_limit_2: DB10.DBX23.3
    '6':
      cabin_button_1: DB10.DBX23.4
      cabin_button_2: DB10.DBX23.5
      cabin_button_3: DB10.DBX23.6
      cabin_button_4: DB10.DBX23.7
      cabin_button_5: DB10.DBX24.0
      cabin_button_6: DB10.DBX24.1
      cabin_button_7: DB10.DBX24.2
      cabin_button_8: DB10.DBX24.3
      cabin_button_9: DB10.DBX24.4
      cabin_button_10: DB10.DBX24.5
      door_open_button: DB10.DBX24.6
      door_close_button: DB10.DBX24.7
      light_curtain: DB10.DBX25.0
      overload: DB10.DBX25.1
      service_mode: DB10.DBX25.2
      car_door_lock: DB10.DBX25.3
      floor_door_lock_1: DB10.DBX25.4
      floor_door_lock_2: DB10.DBX25.5
      floor_door_lock_3: DB10.DBX25.6
      floor_door_lock_4: DB10.DBX25.7
      floor_door_lock_5: DB10.DBX26.0
      floor_door_lock_6: DB10.DBX26.1
      floor_door_lock_7: DB10.DBX26.2
      floor_door_lock_8: DB10.DBX26.3
      floor_door_lock_9: DB10.DBX26.4
      floor_door_lock_10: DB10.DBX26.5
      door_open_done: DB10.DBX26.6
      door_close_done: DB10.DBX26.7
      level_up: DB10.DBX27.0
      level_down: DB10.DBX27.1
      top_limit_1: DB10.DBX27.2
      top_limit_2: DB10.DBX27.3
      bottom_limit_1: DB10.DBX27.4
      bottom_limit_2: DB10.DBX27.5
  auto_run: DB10.DBX27.6
output:
  hall_indicator:
    hall_indicator_up_1: DB11.DBX0.0
    hall_indicator_up_2: DB11.DBX0.1
    hall_indicator_up_3: DB11.DBX0.2
    hall_indicator_up_4: DB11.DBX0.3
    hall_indicator_up_5: DB11.DBX0.4
    hall_indicator_up_6: DB11.DBX0.5
    hall_indicator_up_7: DB11.DBX0.6
    hall_indicator_up_8: DB11.DBX0.7
    hall_indicator_up_9: DB11.DBX1.0
    hall_indicator_down_2: DB11.DBX1.1
    hall_indicator_down_3: DB11.DBX1.2
    hall_indicator_down_4: DB11.DBX1.3
    hall_indicator_down_5: DB11.DBX1.4
    hall_indicator_down_6: DB11.DBX1.5
    hall_indicator_down_7: DB11.DBX1.6
    hall_indicator_down_8: DB11.DBX1.7
    hall_indicator_down_9: DB11.DBX2.0
    hall_indicator_down_10: DB11.DBX2.1
  per_car:
    '1':
      cabin_button_led_1: DB11.DBX2.2
      cabin_button_led_2: DB11.DBX2.3
      cabin_button_led_3: DB11.DBX2.4
      cabin_button_led_4: DB11.DBX2.5
      cabin_button_led_5: DB11.DBX2.6
      cabin_button_led_6: DB11.DBX2.7
      cabin_button_led_7: DB11.DBX3.0
      cabin_button_led_8: DB11.DBX3.1
      cabin_button_led_9: DB11.DBX3.2
      cabin_button_led_10: DB11.DBX3.3
      segment_a: DB11.DBX3.4
      segment_b: DB11.DBX3.5
      segment_c: DB11.DBX3.6
      segment_d: DB11.DBX3.7
      segment_e: DB11.DBX4.0
      segment_f: DB11.DBX4.1
      segment_g: DB11.DBX4.2
      segment_h: DB11.DBX4.3
      segment_i: DB11.DBX4.4
      segment_j: DB11.DBX4.5
      segment_k: DB11.DBX4.6
      segment_l: DB11.DBX4.7
      segment_m: DB11.DBX5.0
      segment_n: DB11.DBX5.1
      up_indicator: DB11.DBX5.2
      down_indicator: DB11.DBX5.3
      fault_indicator: DB11.DBX5.4
      light_indicator: DB11.DBX5.5
      fan_indicator: DB11.DBX5.6
      full_load_indicator: DB11.DBX5.7
      motor_start: DB11.DBX6.0
      up_contactor: DB11.DBX6.1
      down_contactor: DB11.DBX6.2
      high_speed_contactor: DB11.DBX6.3
      low_speed_contactor: DB11.DBX6.4
      door_open_relay: DB11.DBX6.5
      door_close_relay: DB11.DBX6.6
      brake_1: DB11.DBX6.7
      brake_2: DB11.DBX7.0
      brake_3: DB11.DBX7.1
    '2':
      cabin_button_led_1: DB11.DBX7.2
      cabin_button_led_2: DB11.DBX7.3
      cabin_button_led_3: DB11.DBX7.4
      cabin_button_led_4: DB11.DBX7.5
      cabin_button_led_5: DB11.DBX7.6
      cabin_button_led_6: DB11.DBX7.7
      cabin_button_led_7: DB11.DBX8.0
      cabin_button_led_8: DB11.DBX8.1
      cabin_button_led_9: DB11.DBX8.2
      cabin_button_led_10: DB11.DBX8.3
      segment_a: DB11.DBX8.4
      segment_b: DB11.DBX8.5
      segment_c: DB11.DBX8.6
      segment_d: DB11.DBX8.7
      segment_e: DB11.DBX9.0
      segment_f: DB11.DBX9.1
      segment_g: DB11.DBX9.2
      segment_h: DB11.DBX9.3
      segment_i: DB11.DBX9.4
      segment_j: DB11.DBX9.5
      segment_k: DB11.DBX9.6
      segment_l: DB11.DBX9.7
      segment_m: DB11.DBX10.0
      segment_n: DB11.DBX10.1
      up_indicator: DB11.DBX10.2
      down_indicator: DB11.DBX10.3
      fault_indicator: DB11.DBX10.4
      light_indicator: DB11.DBX10.5
      fan_indicator: DB11.DBX10.6
      full_load_indicator: DB11.DBX10.7
      motor_start: DB11.DBX11.0
      up_contactor: DB11.DBX11.1
      down_contactor: DB11.DBX11.2
      high_speed_contactor: DB11.DBX11.3
      low_speed_contactor: DB11.DBX11.4
      door_open_relay: DB11.DBX11.5
      door_close_relay: DB11.DBX11.6
      brake_1: DB11.DBX11.7
      brake_2: DB11.DBX12.0
      brake_3: DB11.DBX12.1
    '3':
      cabin_button_led_1: DB11.DBX12.2
      cabin_button_led_2: DB11.DBX12.3
      cabin_button_led_3: DB11.DBX12.4
      cabin_button_led_4: DB11.DBX12.5
      cabin_button_led_5: DB11.DBX12.6
      cabin_button_led_6: DB11.DBX12.7
      cabin_button_led_7: DB11.DBX13.0
      cabin_button_led_8: DB11.DBX13.1
      cabin_button_led_9: DB11.DBX13.2
      cabin_button_led_10: DB11.DBX13.3
      segment_a: DB11.DBX13.4
      segment_b: DB11.DBX13.5
      segment_c: DB11.DBX13.6
      segment_d: DB11.DBX13.7
      segment_e: DB11.DBX14.0
      segment_f: DB11.DBX14.1
      segment_g: DB11.DBX14.2
      segment_h: DB11.DBX14.3
      segment_i: DB11.DBX14.4
      segment_j: DB11.DBX14.5
      segment_k: DB11.DBX14.6
      segment_l: DB11.DBX14.7
      segment_m: DB11.DBX15.0
      segment_n: DB11.DBX15.1
      up_indicator: DB11.DBX15.2
      down_indicator: DB11.DBX15.3
      fault_indicator: DB11.DBX15.4
      light_indicator: DB11.DBX15.5
      fan_indicator: DB11.DBX15.6
      full_load_indicator: DB11.DBX15.7
      motor_start: DB11.DBX16.0
      up_contactor: DB11.DBX16.1
      down_contactor: DB11.DBX16.2
      high_speed_contactor: DB11.DBX16.3
      low_speed_contactor: DB11.DBX16.4
      door_open_relay: DB11.DBX16.5
      door_close_relay: DB11.DBX16.6
      brake_1: DB11.DBX16.7
      brake_2: DB11.DBX17.0
      brake_3: DB11.DBX17.1
    '4':
      cabin_button_led_1: DB11.DBX17.2
      cabin_button_led_2: DB11.DBX17.3
      cabin_button_led_3: DB11.DBX17.4
      cabin_button_led_4: DB11.DBX17.5
      cabin_button_led_5: DB11.DBX17.6
      cabin_button_led_6: DB11.DBX17.7
      cabin_button_led_7: DB11.DBX18.0
      cabin_button_led_8: DB11.DBX18.1
      cabin_button_led_9: DB11.DBX18.2
      cabin_button_led_10: DB11.DBX18.3
      segment_a: DB11.DBX18.4
      segment_b: DB11.DBX18.5
      segment_c: DB11.DBX18.6
      segment_d: DB11.DBX18.7
      segment_e: DB11.DBX19.0
      segment_f: DB11.DBX19.1
      segment_g: DB11.DBX19.2
      segment_h: DB11.DBX19.3
      segment_i: DB11.DBX19.4
      segment_j: DB11.DBX19.5
      segment_k: DB11.DBX19.6
      segment_l: DB11.DBX19.7
      segment_m: DB11.DBX20.0
      segment_n: DB11.DBX20.1
      up_indicator: DB11.DBX20.2
      down_indicator: DB11.DBX20.3
      fault_indicator: DB11.DBX20.4
      light_indicator: DB11.DBX20.5
      fan_indicator: DB11.DBX20.6
      full_load_indicator: DB11.DBX20.7
      motor_start: DB11.DBX21.0
      up_contactor: DB11.DBX21.1
      down_contactor: DB11.DBX21.2
      high_speed_contactor: DB11.DBX21.3
      low_speed_contactor: DB11.DBX21.4
      door_open_relay: DB11.DBX21.5
      door_close_relay: DB11.DBX21.6
      brake_1: DB11.DBX21.7
      brake_2: DB11.DBX22.0
      brake_3: DB11.DBX22.1
    '5':
      cabin_button_led_1: DB11.DBX22.2
      cabin_button_led_2: DB11.DBX22.3
      cabin_button_led_3: DB11.DBX22.4
      cabin_button_led_4: DB11.DBX22.5
      cabin_button_led_5: DB11.DBX22.6
      cabin_button_led_6: DB11.DBX22.7
      cabin_button_led_7: DB11.DBX23.0
      cabin_button_led_8: DB11.DBX23.1
      cabin_button_led_9: DB11.DBX23.2
      cabin_button_led_10: DB11.DBX23.3
      segment_a: DB11.DBX23.4
      segment_b: DB11.DBX23.5
      segment_c: DB11.DBX23.6
      segment_d: DB11.DBX23.7
      segment_e: DB11.DBX24.0
      segment_f: DB11.DBX24.1
      segment_g: DB11.DBX24.2
      segment_h: DB11.DBX24.3
      segment_i: DB11.DBX24.4
      segment_j: DB11.DBX24.5
      segment_k: DB11.DBX24.6
      segment_l: DB11.DBX24.7
      segment_m: DB11.DBX25.0
      segment_n: DB11.DBX25.1
      up_indicator: DB11.DBX25.2
      down_indicator: DB11.DBX25.3
      fault_indicator: DB11.DBX25.4
      light_indicator: DB11.DBX25.5
      fan_indicator: DB11.DBX25.6
      full_load_indicator: DB11.DBX25.7
      motor_start: DB11.DBX26.0
      up_contactor: DB11.DBX26.1
      down_contactor: DB11.DBX26.2
      high_speed_contactor: DB11.DBX26.3
      low_speed_contactor: DB11.DBX26.4
      door_open_relay: DB11.DBX26.5
      door_close_relay: DB11.DBX26.6
      brake_1: DB11.DBX26.7
      brake_2: DB11.DBX27.0
      brake_3: DB11.DBX27.1
    '6':
      cabin_button_led_1: DB11.DBX27.2
      cabin_button_led_2: DB11.DBX27.3
      cabin_button_led_3: DB11.DBX27.4
      cabin_button_led_4: DB11.DBX27.5
      cabin_button_led_5: DB11.DBX27.6
      cabin_button_led_6: DB11.DBX27.7
      cabin_button_led_7: DB11.DBX28.0
      cabin_button_led_8: DB11.DBX28.1
      cabin_button_led_9: DB11.DBX28.2
      cabin_button_led_10: DB11.DBX28.3
      segment_a: DB11.DBX28.4
      segment_b: DB11.DBX28.5
      segment_c: DB11.DBX28.6
      segment_d: DB11.DBX28.7
      segment_e: DB11.DBX29.0
      segment_f: DB11.DBX29.1
      segment_g: DB11.DBX29.2
      segment_h: DB11.DBX29.3
      segment_i: DB11.DBX29.4
      segment_j: DB11.DBX29.5
      segment_k: DB11.DBX29.6
      segment_l: DB11.DBX29.7
      segment_m: DB11.DBX30.0
      segment_n: DB11.DBX30.1
      up_indicator: DB11.DBX30.2
      down_indicator: DB11.DBX30.3
      fault_indicator: DB11.DBX30.4
      light_indicator: DB11.DBX30.5
      fan_indicator: DB11.DBX30.6
      full_load_indicator: DB11.DBX30.7
      motor_start: DB11.DBX31.0
      up_contactor: DB11.DBX31.1
      down_contactor: DB11.DBX31.2
      high_speed_contactor: DB11.DBX31.3
      low_speed_contactor: DB11.DBX31.4
      door_open_relay: DB11.DBX31.5
      door_close_relay: DB11.DBX31.6
      brake_1: DB11.DBX31.7
      brake_2: DB11.DBX32.0
      brake_3: DB11.DBX32.1
  ready: DB11.DBX32.2
