input:
  hall_call:
    hall_call_up_1: I2.0
    hall_call_up_2: I2.1
    hall_call_up_3: I2.2
    hall_call_up_4: I2.3
    hall_call_up_5: I2.4
    hall_call_up_6: I2.5
    hall_call_up_7: I2.6
    hall_call_up_8: I2.7
    hall_call_up_9: I3.0
    hall_call_down_2: I3.1
    hall_call_down_3: I3.2
    hall_call_down_4: I3.3
    hall_call_down_5: I3.4
    hall_call_down_6: I3.5
    hall_call_down_7: I3.6
    hall_call_down_8: I3.7
    hall_call_down_9: I4.0
    hall_call_down_10: I4.1
  per_car:
    '1':
      cabin_button_1: I4.2
      cabin_button_2: I4.3
      cabin_button_3: I4.4
      cabin_button_4: I4.5
      cabin_button_5: I4.6
      cabin_button_6: I4.7
      cabin_button_7: I5.0
      cabin_button_8: I5.1
      cabin_button_9: I5.2
      cabin_button_10: I5.3
      door_open_button: I5.4
      door_close_button: I5.5
      light_curtain: I5.6
      overload: I5.7
      service_mode: I6.0
      car_door_lock: I6.1
      floor_door_lock_1: I6.2
      floor_door_lock_2: I6.3
      floor_door_lock_3: I6.4
      floor_door_lock_4: I6.5
      floor_door_lock_5: I6.6
      floor_door_lock_6: I6.7
      floor_door_lock_7: I7.0
      floor_door_lock_8: I7.1
      floor_door_lock_9: I7.2
      floor_door_lock_10: I7.3
      door_open_done: I7.4
      door_close_done: I7.5
      level_up: I7.6
      level_down: I7.7
      top_limit_1: I8.0
      top_limit_2: I8.1
      bottom_limit_1: I8.2
      bottom_limit_2: I8.3
    '2':
      cabin_button_1: I8.4
      cabin_button_2: I8.5
      cabin_button_3: I8.6
      cabin_button_4: I8.7
      cabin_button_5: I9.0
      cabin_button_6: I9.1
      cabin_button_7: I9.2
      cabin_button_8: I9.3
      cabin_button_9: I9.4
      cabin_button_10: I9.5
      door_open_button: I9.6
      door_close_button: I9.7
      light_curtain: I10.0
      overload: I10.1
      service_mode: I10.2
      car_door_lock: I10.3
      floor_door_lock_1: I10.4
      floor_door_lock_2: I10.5
      floor_door_lock_3: I10.6
      floor_door_lock_4: I10.7
      floor_door_lock_5: I11.0
      floor_door_lock_6: I11.1
      floor_door_lock_7: I11.2
      floor_door_lock_8: I11.3
      floor_door_lock_9: I11.4
      floor_door_lock_10: I11.5
      door_open_done: I11.6
      door_close_done: I11.7
      level_up: I12.0
      level_down: I12.1
      top_limit_1: I12.2
      top_limit_2: I12.3
      bottom_limit_1: I12.4
      bottom_limit_2: I12.5
    '3':
      cabin_button_1: I12.6
      cabin_button_2: I12.7
      cabin_button_3: I13.0
      cabin_button_4: I13.1
      cabin_button_5: I13.2
      cabin_button_6: I13.3
      cabin_button_7: I13.4
      cabin_button_8: I13.5
      cabin_button_9: I13.6
      cabin_button_10: I13.7
      door_open_button: I14.0
      door_close_button: I14.1
      light_curtain: I14.2
      overload: I14.3
      service_mode: I14.4
      car_door_lock: I14.5
      floor_door_lock_1: I14.6
      floor_door_lock_2: I14.7
      floor_door_lock_3: I15.0
      floor_door_lock_4: I15.1
      floor_door_lock_5: I15.2
      floor_door_lock_6: I15.3
      floor_door_lock_7: I15.4
      floor_door_lock_8: I15.5
      floor_door_lock_9: I15.6
      floor_door_lock_10: I15.7
      door_open_done: I16.0
      door_close_done: I16.1
      level_up: I16.2
      level_down: I16.3
      top_limit_1: I16.4
      top_limit_2: I16.5
      bottom_limit_1: I16.6
      bottom_limit_2: I16.7
    '4':
      cabin_button_1: I17.0
      cabin_button_2: I17.1
      cabin_button_3: I17.2
      cabin_button_4: I17.3
      cabin_button_5: I17.4
      cabin_button_6: I17.5
      cabin_button_7: I17.6
      cabin_button_8: I17.7
      cabin_button_9: I18.0
      cabin_button_10: I18.1
      door_open_button: I18.2
      door_close_button: I18.3
      light_curtain: I18.4
      overload: I18.5
      service_mode: I18.6
      car_door_lock: I18.7
      floor_door_lock_1: I19.0
      floor_door_lock_2: I19.1
      floor_door_lock_3: I19.2
      floor_door_lock_4: I19.3
      floor_door_lock_5: I19.4
      floor_door_lock_6: I19.5
      floor_door_lock_7: I19.6
      floor_door_lock_8: I19.7
      floor_door_lock_9: I20.0
      floor_door_lock_10: I20.1
      door_open_done: I20.2
      door_close_done: I20.3
      level_up: I20.4
      level_down: I20.5
      top_limit_1: I20.6
      top_limit_2: I20.7
      bottom_limit_1: I21.0
      bottom_limit_2: I21.1
    '5':
      cabin_button_1: I21.2
      cabin_button_2: I21.3
      cabin_button_3: I21.4
      cabin_button_4: I21.5
      cabin_button_5: I21.6
      cabin_button_6: I21.7
      cabin_button_7: I22.0
      cabin_button_8: I22.1
      cabin_button_9: I22.2
      cabin_button_10: I22.3
      door_open_button: I22.4
      door_close_button: I22.5
      light_curtain: I22.6
      overload: I22.7
      service_mode: I23.0
      car_door_lock: I23.1
      floor_door_lock_1: I23.2
      floor_door_lock_2: I23.3
      floor_door_lock_3: I23.4
      floor_door_lock_4: I23.5
      floor_door_lock_5: I23.6
      floor_door_lock_6: I23.7
      floor_door_lock_7: I24.0
      floor_door_lock_8: I24.1
      floor_door_lock_9: I24.2
      floor_door_lock_10: I24.3
      door_open_done: I24.4
      door_close_done: I24.5
      level_up: I24.6
      level_down: I24.7
      top_limit_1: I25.0
      top_limit_2: I25.1
      bottom_limit_1: I25.2
      bottom_limit_2: I25.3
    '6':
      cabin_button_1: I25.4
      cabin_button_2: I25.5
      cabin_button_3: I25.6
      cabin_button_4: I25.7
      cabin_button_5: I26.0
      cabin_button_6: I26.1
      cabin_button_7: I26.2
      cabin_button_8: I26.3
      cabin_button_9: I26.4
      cabin_button_10: I26.5
      door_open_button: I26.6
      door_close_button: I26.7
      light_curtain: I27.0
      overload: I27.1
      service_mode: I27.2
      car_door_lock: I27.3
      floor_door_lock_1: I27.4
      floor_door_lock_2: I27.5
      floor_door_lock_3: I27.6
      floor_door_lock_4: I27.7
      floor_door_lock_5: I28.0
      floor_door_lock_6: I28.1
      floor_door_lock_7: I28.2
      floor_door_lock_8: I28.3
      floor_door_lock_9: I28.4
      floor_door_lock_10: I28.5
      door_open_done: I28.6
      door_close_done: I28.7
      level_up: I29.0
      level_down: I29.1
      top_limit_1: I29.2
      top_limit_2: I29.3
      bottom_limit_1: I29.4
      bottom_limit_2: I29.5
  auto_run: I29.6
output:
  hall_indicator:
    hall_indicator_up_1: DB11.DBX0.0
    hall_indicator_up_2: DB11.DBX0.1
    hall_indicator_up_3: DB11.DBX0.2
    hall_indicator_up_4: DB11.DBX0.3
    hall_indicator_up_5: DB11.DBX0.4
    hall_indicator_up_6: DB11.DBX0.5
    hall_indicator_up_7: DB11.DBX0.6
    hall_indicator_up_8: DB11.DBX0.7
    hall_indicator_up_9: DB11.DBX1.0
    hall_indicator_down_2: DB11.DBX1.1
    hall_indicator_down_3: DB11.DBX1.2
    hall_indicator_down_4: DB11.DBX1.3
    hall_indicator_down_5: DB11.DBX1.4
    hall_indicator_down_6: DB11.DBX1.5
    hall_indicator_down_7: DB11.DBX1.6
    hall_indicator_down_8: DB11.DBX1.7
    hall_indicator_down_9: DB11.DBX2.0
    hall_indicator_down_10: DB11.DBX2.1
  per_car:
    '1':
      cabin_button_led_1: DB11.DBX2.2
      cabin_button_led_2: DB11.DBX2.3
      cabin_button_led_3: DB11.DBX2.4
      cabin_button_led_4: DB11.DBX2.5
      cabin_button_led_5: DB11.DBX2.6
      cabin_button_led_6: DB11.DBX2.7
      cabin_button_led_7: DB11.DBX3.0
      cabin_button_led_8: DB11.DBX3.1
      cabin_button_led_9: DB11.DBX3.2
      cabin_button_led_10: DB11.DBX3.3
      segment_a: DB11.DBX3.4
      segment_b: DB11.DBX3.5
      segment_c: DB11.DBX3.6
      segment_d: DB11.DBX3.7
      segment_e: DB11.DBX4.0
      segment_f: DB11.DBX4.1
      segment_g: DB11.DBX4.2
      segment_h: DB11.DBX4.3
      segment_i: DB11.DBX4.4
      segment_j: DB11.DBX4.5
      segment_k: DB11.DBX4.6
      segment_l: DB11.DBX4.7
      segment_m: DB11.DBX5.0
      segment_n: DB11.DBX5.1
      up_indicator: DB11.DBX5.2
      down_indicator: DB11.DBX5.3
      fault_indicator: DB11.DBX5.4
      light_indicator: DB11.DBX5.5
      fan_indicator: DB11.DBX5.6
      full_load_indicator: DB11.DBX5.7
      motor_start: DB11.DBX6.0
      up_contactor: DB11.DBX6.1
      down_contactor: DB11.DBX6.2
      high_speed_contactor: DB11.DBX6.3
      low_speed_contactor: DB11.DBX6.4
      door_open_relay: DB11.DBX6.5
      door_close_relay: DB11.DBX6.6
      brake_1: DB11.DBX6.7
      brake_2: DB11.DBX7.0
      brake_3: DB11.DBX7.1
    '2':
      cabin_button_led_1: DB11.DBX7.2
      cabin_button_led_2: DB11.DBX7.3
      cabin_button_led_3: DB11.DBX7.4
      cabin_button_led_4: DB11.DBX7.5
      cabin_button_led_5: DB11.DBX7.6
      cabin_button_led_6: DB11.DBX7.7
      cabin_button_led_7: DB11.DBX8.0
      cabin_button_led_8: DB11.DBX8.1
      cabin_button_led_9: DB11.DBX8.2
      cabin_button_led_10: DB11.DBX8.3
      segment_a: DB11.DBX8.4
      segment_b: DB11.DBX8.5
      segment_c: DB11.DBX8.6
      segment_d: DB11.DBX8.7
      segment_e: DB11.DBX9.0
      segment_f: DB11.DBX9.1
      segment_g: DB11.DBX9.2
      segment_h: DB11.DBX9.3
      segment_i: DB11.DBX9.4
      segment_j: DB11.DBX9.5
      segment_k: DB11.DBX9.6
      segment_l: DB11.DBX9.7
      segment_m: DB11.DBX10.0
      segment_n: DB11.DBX10.1
      up_indicator: DB11.DBX10.2
      down_indicator: DB11.DBX10.3
      fault_indicator: DB11.DBX10.4
      light_indicator: DB11.DBX10.5
      fan_indicator: DB11.DBX10.6
      full_load_indicator: DB11.DBX10.7
      motor_start: DB11.DBX11.0
      up_contactor: DB11.DBX11.1
      down_contactor: DB11.DBX11.2
      high_speed_contactor: DB11.DBX11.3
      low_speed_contactor: DB11.DBX11.4
      door_open_relay: DB11.DBX11.5
      door_close_relay: DB11.DBX11.6
      brake_1: DB11.DBX11.7
      brake_2: DB11.DBX12.0
      brake_3: DB11.DBX12.1
    '3':
      cabin_button_led_1: DB11.DBX12.2
      cabin_button_led_2: DB11.DBX12.3
      cabin_button_led_3: DB11.DBX12.4
      cabin_button_led_4: DB11.DBX12.5
      cabin_button_led_5: DB11.DBX12.6
      cabin_button_led_6: DB11.DBX12.7
      cabin_button_led_7: DB11.DBX13.0
      cabin_button_led_8: DB11.DBX13.1
      cabin_button_led_9: DB11.DBX13.2
      cabin_button_led_10: DB11.DBX13.3
      segment_a: DB11.DBX13.4
      segment_b: DB11.DBX13.5
      segment_c: DB11.DBX13.6
      segment_d: DB11.DBX13.7
      segment_e: DB11.DBX14.0
      segment_f: DB11.DBX14.1
      segment_g: DB11.DBX14.2
      segment_h: DB11.DBX14.3
      segment_i: DB11.DBX14.4
      segment_j: DB11.DBX14.5
      segment_k: DB11.DBX14.6
      segment_l: DB11.DBX14.7
      segment_m: DB11.DBX15.0
      segment_n: DB11.DBX15.1
      up_indicator: DB11.DBX15.2
      down_indicator: DB11.DBX15.3
      fault_indicator: DB11.DBX15.4
      light_indicator: DB11.DBX15.5
      fan_indicator: DB11.DBX15.6
      full_load_indicator: DB11.DBX15.7
      motor_start: DB11.DBX16.0
      up_contactor: DB11.DBX16.1
      down_contactor: DB11.DBX16.2
      high_speed_contactor: DB11.DBX16.3
      low_speed_contactor: DB11.DBX16.4
      door_open_relay: DB11.DBX16.5
      door_close_relay: DB11.DBX16.6
      brake_1: DB11.DBX16.7
      brake_2: DB11.DBX17.0
      brake_3: DB11.DBX17.1
    '4':
      cabin_button_led_1: DB11.DBX17.2
      cabin_button_led_2: DB11.DBX17.3
      cabin_button_led_3: DB11.DBX17.4
      cabin_button_led_4: DB11.DBX17.5
      cabin_button_led_5: DB11.DBX17.6
      cabin_button_led_6: DB11.DBX17.7
      cabin_button_led_7: DB11.DBX18.0
      cabin_button_led_8: DB11.DBX18.1
      cabin_button_led_9: DB11.DBX18.2
      cabin_button_led_10: DB11.DBX18.3
      segment_a: DB11.DBX18.4
      segment_b: DB11.DBX18.5
      segment_c: DB11.DBX18.6
      segment_d: DB11.DBX18.7
      segment_e: DB11.DBX19.0
      segment_f: DB11.DBX19.1
      segment_g: DB11.DBX19.2
      segment_h: DB11.DBX19.3
      segment_i: DB11.DBX19.4
      segment_j: DB11.DBX19.5
      segment_k: DB11.DBX19.6
      segment_l: DB11.DBX19.7
      segment_m: DB11.DBX20.0
      segment_n: DB11.DBX20.1
      up_indicator: DB11.DBX20.2
      down_indicator: DB11.DBX20.3
      fault_indicator: DB11.DBX20.4
      light_indicator: DB11.DBX20.5
      fan_indicator: DB11.DBX20.6
      full_load_indicator: DB11.DBX20.7
      motor_start: DB11.DBX21.0
      up_contactor: DB11.DBX21.1
      down_contactor: DB11.DBX21.2
      high_speed_contactor: DB11.DBX21.3
      low_speed_contactor: DB11.DBX21.4
      door_open_relay: DB11.DBX21.5
      door_close_relay: DB11.DBX21.6
      brake_1: DB11.DBX21.7
      brake_2: DB11.DBX22.0
      brake_3: DB11.DBX22.1
    '5':
      cabin_button_led_1: DB11.DBX22.2
      cabin_button_led_2: DB11.DBX22.3
      cabin_button_led_3: DB11.DBX22.4
      cabin_button_led_4: DB11.DBX22.5
      cabin_button_led_5: DB11.DBX22.6
      cabin_button_led_6: DB11.DBX22.7
      cabin_button_led_7: DB11.DBX23.0
      cabin_button_led_8: DB11.DBX23.1
      cabin_button_led_9: DB11.DBX23.2
      cabin_button_led_10: DB11.DBX23.3
      segment_a: DB11.DBX23.4
      segment_b: DB11.DBX23.5
      segment_c: DB11.DBX23.6
      segment_d: DB11.DBX23.7
      segment_e: DB11.DBX24.0
      segment_f: DB11.DBX24.1
      segment_g: DB11.DBX24.2
      segment_h: DB11.DBX24.3
      segment_i: DB11.DBX24.4
      segment_j: DB11.DBX24.5
      segment_k: DB11.DBX24.6
      segment_l: DB11.DBX24.7
      segment_m: DB11.DBX25.0
      segment_n: DB11.DBX25.1
      up_indicator: DB11.DBX25.2
      down_indicator: DB11.DBX25.3
      fault_indicator: DB11.DBX25.4
      light_indicator: DB11.DBX25.5
      fan_indicator: DB11.DBX25.6
      full_load_indicator: DB11.DBX25.7
      motor_start: DB11.DBX26.0
      up_contactor: DB11.DBX26.1
      down_contactor: DB11.DBX26.2
      high_speed_contactor: DB11.DBX26.3
      low_speed_contactor: DB11.DBX26.4
      door_open_relay: DB11.DBX26.5
      door_close_relay: DB11.DBX26.6
      brake_1: DB11.DBX26.7
      brake_2: DB11.DBX27.0
      brake_3: DB11.DBX27.1
    '6':
      cabin_button_led_1: DB11.DBX27.2
      cabin_button_led_2: DB11.DBX27.3
      cabin_button_led_3: DB11.DBX27.4
      cabin_button_led_4: DB11.DBX27.5
      cabin_button_led_5: DB11.DBX27.6
      cabin_button_led_6: DB11.DBX27.7
      cabin_button_led_7: DB11.DBX28.0
      cabin_button_led_8: DB11.DBX28.1
      cabin_button_led_9: DB11.DBX28.2
      cabin_button_led_10: DB11.DBX28.3
      segment_a: DB11.DBX28.4
      segment_b: DB11.DBX28.5
      segment_c: DB11.DBX28.6
      segment_d: DB11.DBX28.7
      segment_e: DB11.DBX29.0
      segment_f: DB11.DBX29.1
      segment_g: DB11.DBX29.2
      segment_h: DB11.DBX29.3
      segment_i: DB11.DBX29.4
      segment_j: DB11.DBX29.5
      segment_k: DB11.DBX29.6
      segment_l: DB11.DBX29.7
      segment_m: DB11.DBX30.0
      segment_n: DB11.DBX30.1
      up_indicator: DB11.DBX30.2
      down_indicator: DB11.DBX30.3
      fault_indicator: DB11.DBX30.4
      light_indicator: DB11.DBX30.5
      fan_indicator: DB11.DBX30.6
      full_load_indicator: DB11.DBX30.7
      motor_start: DB11.DBX31.0
      up_contactor: DB11.DBX31.1
      down_contactor: DB11.DBX31.2
      high_speed_contactor: DB11.DBX31.3
      low_speed_contactor: DB11.DBX31.4
      door_open_relay: DB11.DBX31.5
      door_close_relay: DB11.DBX31.6
      brake_1: DB11.DBX31.7
      brake_2: DB11.DBX32.0
      brake_3: DB11.DBX32.1
  ready: DB11.DBX32.2
